services:
  db:
    image: postgres:17-alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ali
      POSTGRES_PASSWORD: 555
      POSTGRES_DB: trans_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ali -d trans_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - bridge
    
  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080
    networks:
      - bridge

networks:
  bridge:
    driver: bridge